# compose syntax version.
version: "3.6"

# services declaration.
services:
  # Web Application
  despacho:
    build:
      args:
        user: apppedido
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hillushilbert/app-pedidos:latest
    # volumes:
    #   - .:/var/www/
    container_name: despacho-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - pucminas
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8020"
    # command: bash -c "composer install && php artisan command:despacho"

    # ports:
    #   - 8020:8020

networks:
  pucminas:
    external: true