version: "3"
services:
  mongo_express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pucminas
      ME_CONFIG_MONGODB_URL: mongodb://mongo_root:pucminas@mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks: ['pucminas']
  mongodb:
    container_name: pipeline_db
    image: mongo:latest
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
      - pedidos_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_root
      - MONGO_INITDB_ROOT_PASSWORD=pucminas
      - APP_USER=app_user
      - APP_PWD=pucminas
      - DB_NAME=Pedidos
      - DB_COLLECTION_NAME=pendentes
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
    networks: ['pucminas']
  pipeline_pedidos_1:
    build:
      args:
        user: apppipeline
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: pipeline_pedidos_1
    image: andremoreirafocus/pipeline_pedidos:latest
    volumes:
      - ./config/pipeline.conf/:/var/app/pipeline.conf
      - ./pedidoenviar.json/:/var/app/pedidoenviar.json
    networks: ['pucminas']
    depends_on:
      - mongodb
  pipeline_pedidos_2:
    container_name: pipeline_pedidos_2
    image: andremoreirafocus/pipeline_pedidos:latest
    volumes:
      # - ./src/pipeline.conf/:/var/app/pipeline.conf
      - ./config/pipeline.conf/:/var/app/pipeline.conf
      - ./pedidoenviar.json/:/var/app/pedidoenviar.json
    networks: ['pucminas']
    depends_on:
      - mongodb
volumes:
  pedidos_data:
networks:
  pucminas:
    external: true

