# compose syntax version.
version: "3.6"

# services declaration.
services:
  # Web Application
  pedidos:
    build:
      args:
        user: apppedido
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hillushilbert/app-pedidos:latest
    container_name: pedidos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - pucminas
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8010"
    ports:
      - 8010:8010

  roteamento:
    image: hillushilbert/app-pedidos:latest
    container_name: pedidos-roteamento
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - pucminas
    command: 
     - php 
     - artisan
     - command:roteamento


networks:
  pucminas:
    external: true