# compose syntax version.
version: "3.6"

# services declaration.
services:
  # Web Application
  micapp:
    build:
      args:
        user: appcadastro
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    image: hillushilbert/app-mic:latest
    container_name: mic-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - pucminas
  #Nginx Application
  mic:
    image: nginx:alpine
    container_name: mic-nginx
    restart: unless-stopped
    ports:
      - 8040:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - pucminas

networks:
  pucminas:
    external: true