# compose syntax version.
version: "3.6"

# services declaration.
services:
  # Web Application
  sge:
    build:
      args:
        user: appsge
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hillushilbert/app-sge:latest
    # volumes:
    #   - .:/var/www/
    container_name: sge-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    networks:
      - pucminas
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8030"
    ports:
      - 8030:8030

networks:
  pucminas:
    external: true